### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=GoLand

###
POST http://localhost:9999/api/v1/auth/register
Content-Type: application/json

{
  "login": "Maftuna9",
  "password":"adminadmin",
  "role": "admin"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "login": "Maftuna6",
  "password":"adminadmin",
  "role": "admin"
}


###
POST http://localhost:9999/api/v1/auth/register
Content-Type: application/json

{
  "login": "Rayhona",
  "password":"adminadmin",
  "role": "admin"
}

###
POST http://localhost:9999/api/v1/auth/login
Content-Type: application/json

{
  "login": "Rayhona",
  "password":"adminadmin",
  "role": "admin"
}

> {%
    client.global.set("authToken", response.body.authToken);
%}

###
POST http://localhost:9999/api/v1/admin/close-expired
Authorization: Bearer {{authToken}}