###
POST http://localhost:9999/api/v1/auth/register
Content-Type: application/json

{
  "login": "Maftuna",
  "password":"adminadmin",
  "role": "admin"
}

###
POST http://localhost:9999/api/v1/auth/login
Content-Type: application/json

{
  "login": "Maftuna",
  "password":"adminadmin",
  "role": "admin"
}


###
POST http://localhost:9999/api/v1/auth/register
Content-Type: application/json

{
  "login": "Rayhona",
  "password":"adminadmin",
  "role": "admin"
}

###
POST http://localhost:9999/api/v1/auth/login
Content-Type: application/json

{
  "login": "Rayhona",
  "password":"adminadmin",
  "role": "admin"
}

> {%
    client.global.set("accessToken", response.body.access_token);
    client.global.set("refreshToken", response.body.refresh_token);
%}

###
GET http://localhost:9999/api/v1/admin/lots
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
POST http://localhost:9999/api/v1/admin/close-expired
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
POST http://localhost:9999/api/v1/lots/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODUzOTc3OTIsInJvbGUiOiJhZG1pbiIsInVpZCI6MX0.EkYwLPtvKQZgHeMB96TZMwYdoEJ-tC6Sh8s5R_xlsZQ

{
  "title": "Home",
  "description": "good phone",
  "startPrice": 20000000,
  "photo": "https://i.pinimg.com/474x/bd/a8/0e/bda80e9324bd6d5c83b84b6eac5a1e5d.jpg",
  "endsAt": "2026-12-31T23:59:59Z",
  "status": "live",
  "category": "home"
}

###
GET http://localhost:9999/api/v1/lots
Content-Type: application/json



###
POST http://localhost:9999/api/v1/auth/register
Content-Type: application/json

{
  "login": "bidder2",
  "password":"bidderbidder",
  "role": "bidder"
}

###
###
POST http://localhost:9999/api/v1/auth/login
Content-Type: application/json

{
  "login": "Rayhona",
  "password":"adminadmin",
  "role": "admin"
}

> {%
    client.global.set("accessToken", response.body.access_token);
    client.global.set("refreshToken", response.body.refresh_token);
%}

###
POST http://localhost:9999/api/v1/lots/new
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "Iphone",
  "description": "good phone",
  "startPrice": 12000,
  "category": "electronics",
  "photo": "https://i.pinimg.com/474x/bd/a8/0e/bda80e9324bd6d5c83b84b6eac5a1e5d.jpg",
  "endsAt": "2026-12-31T23:59:59Z",
  "status": "live"
}

###
PUT http://localhost:9999/api/v1/lots/15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODQ3MjY4MTQsInJvbGUiOiJhZG1pbiIsInVpZCI6MX0.aMYgagCndah7J4LJU8J9qp9Te82SZuLP1AtItbrqmnQ

{
  "title": "Iphone 15",
  "description": "even better phone",
  "startPrice": 15000,
  "photo": " ",
  "endsAt": "2026-12-31T23:59:59Z"
}

###
DELETE http://localhost:9999/api/v1/lots/22
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODQ3Mjg5NDYsInJvbGUiOiJhZG1pbiIsInVpZCI6MX0.4cL0nnSTKuXcBzCjZaaXeFl3kB0Xx7pB088O60L8ddM

###
PUT http://localhost:9999/api/v1/lots/3/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODUzOTc3OTIsInJvbGUiOiJhZG1pbiIsInVpZCI6MX0.EkYwLPtvKQZgHeMB96TZMwYdoEJ-tC6Sh8s5R_xlsZQ

{
  "status": "closed"
}

###
POST http://localhost:9999/api/v1/lots/11/photo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODUwMDk0MjcsInJvbGUiOiJhZG1pbiIsInVpZCI6MX0.SwvXWGvKkiEAm_hva7BGH2aBunVTb6sseSIXFIsR8SA
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="photo"; filename="test.jpg"
Content-Type: image/jpeg

< /Users/a1/Pictures/images/99C8B763-5990-42A1-97CC-F4DA88204A85_4_5005_c.jpeg
--WebAppBoundary--

###
GET http://localhost:9999/api/v1/lots/11/photo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODUwMDk0MjcsInJvbGUiOiJhZG1pbiIsInVpZCI6MX0.SwvXWGvKkiEAm_hva7BGH2aBunVTb6sseSIXFIsR8SA

###
PUT http://localhost:9999/api/v1/admin/lots/2/moderate
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "approve": true
}

###
GET http://localhost:9999/api/v1/admin/stats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODUyMjkzNjUsInJvbGUiOiJiaWRkZXIiLCJ1aWQiOjN9.imjI95-Z-ibf01s0DSpzAo8k9Ltjj3HGTZ1ZiZuxgZI

###

GET http://localhost:9999/api/v1/lots/19/bids
Content-Type:   application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODUzMTExNzgsInJvbGUiOiJiaWRkZXIiLCJ1aWQiOjN9.YvhbDLSOV87OZ1rxxPBYRZHLY5B10N4lA3EJMBjwlBA

###
POST http://localhost:9999/api/v1/lots/20/bid
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODUzMzMzNDgsInJvbGUiOiJiaWRkZXIiLCJ1aWQiOjN9.bltfXklz_LjkVKTKBtIKhIwlm00s3u9vwNBWdNFRDtY

{
  "amount": 20000
}

###
GET http://localhost:9999/api/v1/seller/stats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3ODUzOTg4NTcsInJvbGUiOiJhZG1pbiIsInVpZCI6MX0.PlRqPdkiVW4qbEcEp-I9wkf6Ai0s-NPf1FzIOu-0kjc
